#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-rocks.shy.VacuumTube}"

echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
zypak-wrapper /app/bin/vacuumtube/vacuumtube "${FLAGS[@]}" "$@"